server:
  port: 0
base-url:
  context: /kasper/v1

bootstrap:
  bip: "127.0.0.1"
  bport: 55555

log:
  identifierKey: UUID
socket:
  timeout: 10000

node:
  req-url: "http://{ip}:{port}/${base-url.context}/downloadFile/{file}"

## MULTIPART (MultipartProperties)
# Enable multipart uploads
spring.servlet.multipart.enabled: true
# Threshold after which files are written to disk.
spring.servlet.multipart.file-size-threshold: 2KB
# Max file size.
spring.servlet.multipart.max-file-size: 200MB
# Max Request Size
spring.servlet.multipart.max-request-size: 215MB

## File Storage Properties
# Please change this to the path where you want the uploaded files to be stored.
file:
  upload-dir: "classpath:/drive"
  download-dir: "classpath:/downloads"

search:
  hops: 5
msg:
  register: "REG {ip} {port} {username}"
  un-register: "UNREG {ip} {port} {username}"
  join: "JOIN {ip} {port}"
  join-reply: "JOINOK {value}"
  leave: "LEAVE {ip} {port}"
  leave-reply: "LEAVEOK {value}"
  search: "SER {ip} {port} {file name} {hops} {uniqId}"
  search-reply: "SEROK {No of Files} {ip} {port} {hops} {file names}"
  search-notify: "SERNOTIFY"

file-serch:
  directCall: "Search"


