server:
  port: 8081
base-url:
  context: /kasper/v1

bootstrap:
  bip: "127.0.0.1"
  bport: 55555

log:
  identifierKey: UUID

node:
  req-url: "http://{ip}:{port}/${base-url.context}/node/"

msg:
  join: "JOIN {ip} {port}"
  leave: "LEAVE {ip} {port}"


